name: CMake

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      shell: bash
      run: |
        sudo apt update -y
        sudo apt install -y libgflags-dev libcurl4-openssl-dev libssl-dev libaio-dev libnl-3-dev libnl-genl-3-dev libzstd-dev
        sudo apt install -y uuid-dev libjson-c-dev libkmod-dev libsystemd-dev autoconf automake libtool libpci-dev nasm
        wget https://github.com/google/googletest/archive/refs/tags/release-1.11.0.tar.gz
        tar -zxvf release-1.11.0.tar.gz
        cd googletest-release-1.11.0/
        cmake CMakeLists.txt
        make
        sudo make install

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: |
        git submodule update --init
        cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_TESTING=1 -DENABLE_DSA=1 -DENABLE_ISAL=1

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: make -j64

    - name: E2E Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: |
        sudo make install
        sudo systemctl enable /opt/overlaybd/overlaybd-tcmu.service
        sudo systemctl start overlaybd-tcmu
        sudo systemctl status overlaybd-tcmu
        sudo mkdir -p /var/lib/overlaybd/test/
        sudo mkdir -p /sys/kernel/config/target/core/user_1/vol1
        echo -n dev_config=overlaybd/${{github.workspace}}/src/example_config/redis.obd.config.json | sudo tee /sys/kernel/config/target/core/user_1/vol1/control
        echo -n 1 | sudo tee /sys/kernel/config/target/core/user_1/vol1/enable
        sudo mkdir -p /sys/kernel/config/target/loopback/naa.123456789abcdef/tpgt_1/lun/lun_0
        echo -n "naa.123456789abcdef" | sudo tee /sys/kernel/config/target/loopback/naa.123456789abcdef/tpgt_1/nexus
        sudo ln -s /sys/kernel/config/target/core/user_1/vol1 /sys/kernel/config/target/loopback/naa.123456789abcdef/tpgt_1/lun/lun_0/vol1
        lsblk
        sudo apt install -y lsscsi
        dev=`lsscsi | grep TCMU | awk '{print $7}'`
        echo $dev
        sudo mkdir mp
        sudo mount -o ro $dev mp
        ls mp

    - name: Unit Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: ctest -j8 --output-on-failure -C $BUILD_TYPE






